---
title: "BPM"
author: "Chris Gallo"
date: '2020-12-15'
slug: bpm-minutes
tags:
- R Markdown
categories: R
type: post
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=12, fig.height=8)
```

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(ggrepel)

theme_me <- function () {
  theme_minimal(base_size = 15) %+replace%
    theme (
      plot.title = element_text(hjust = 0.5),
      plot.subtitle = element_text(
        hjust = 0.5,
        vjust = -2,
        lineheight = 0.9,
        size = 10
      ),
      plot.caption = element_text(size = 8, hjust = 1),
      panel.grid.minor = element_blank(),
      plot.background = element_rect(fill = "#c9e1f1", color = "#c9e1f1")
    )
}

bpm <- tibble::tribble(
~Player, ~Min, ~BPM,
"Caleb Love",76.3,-1.8,
"RJ Davis",75.4,1.5,
"Leaky Black",72.1,3.8,
"Garrison Brooks",69.6,4,
"Armando Bacot",56.7,8.1,
"Day'Ron Sharpe",45.4,13.9,
"Andrew Platek",37.1,7.3,
"Kerwin Walton",25.8,-1.3,
"Walker Kessler",21.3,4,
"Puff Johnson",9.6,-2.4
)

ggplot(bpm, aes(x = Min, y = BPM, label = Player))+
  geom_text_repel(aes(colour = Player), fontface = "bold", size=4) +
  xlim(0, 80) +
  ylim(-5, 15) +
 theme_me() +
 theme(legend.position = "none") +
  geom_hline(yintercept = 0, lty = 2) +
  labs(
    x = "Minutes Percentage",
    y = "BPM",
    title = "Carolina: Minutes Percentage and Box Score Plus/Minus Through Six Games",
    subtitle ="BPM estimates a player's contribution. Six games is a small sample size",
    caption = "@dadgumboxscores"
  )
```

This shows minutes percentage + box score plus/minus through six games this season for Carolina basketball.

It's a super small sample size of six games.

Only players shown that have at least 5 percent of minutes played. 

Code is below . . .

```
library(tidyverse)
library(ggrepel)

theme_me <- function () {
  theme_minimal(base_size = 15, base_family = "RobotoCondensed-Regular") %+replace%
    theme (
      plot.title = element_text(hjust = 0.5),
      plot.subtitle = element_text(
        hjust = 0.5,
        vjust = -2,
        lineheight = 0.9,
        size = 10
      ),
      plot.caption = element_text(size = 8, hjust = 1),
      panel.grid.minor = element_blank(),
      plot.background = element_rect(fill = "#c9e1f1", color = "#c9e1f1")
    )
}

bpm <- tibble::tribble(
~Player, ~Min, ~BPM,
"Caleb Love",76.3,-1.8,
"RJ Davis",75.4,1.5,
"Leaky Black",72.1,3.8,
"Garrison Brooks",69.6,4,
"Armando Bacot",56.7,8.1,
"Day'Ron Sharpe",45.4,13.9,
"Andrew Platek",37.1,7.3,
"Kerwin Walton",25.8,-1.3,
"Walker Kessler",21.3,4,
"Puff Johnson",9.6,-2.4
)

ggplot(bpm, aes(x = Min, y = BPM, label = Player))+
  geom_text_repel(aes(colour = Player), fontface = "bold", size=4) +
  xlim(0, 80) +
  ylim(-5, 15) +
 theme_me() +
 theme(legend.position = "none") +
  geom_hline(yintercept = 0, lty = 2) +
  labs(
    x = "Minutes Percentage",
    y = "BPM",
    title = "Carolina: Minutes Percentage and Box Score Plus/Minus Through Six Games",
    subtitle ="BPM estimates a player's contribution. Six games is a small sample size",
    caption = "@dadgumboxscores"
  )
```
