---
title: "Three-Point Changes"
author: "Chris Gallo"
date: '2020-12-17'
slug: three-point-changes
tags:
- R Markdown
categories: R
type: post
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=12, fig.height=8)
```

```{r, echo=FALSE, message=FALSE}
library(tidyverse)

theme_me <- function () {
  theme_minimal(base_size = 15) %+replace%
    theme (
      plot.title = element_text(hjust = 0.5),
      plot.subtitle = element_text(
        hjust = 0.5,
        vjust = -2,
        lineheight = 0.9,
        size = 10
      ),
      plot.caption = element_text(size = 8, hjust = 1),
      panel.grid.minor = element_blank(),
      plot.background = element_rect(fill = "#c9e1f1", color = "#c9e1f1")
    )
}


three <- tibble::tribble(
  ~Season,~pct,
  2021,27.0,
  2020,30.4,
  2019,36.2,
  2018,35.9,
  2017,35.5,
  2016,32.7,
  2015,35.8,
  2014,33.6,
  2013,37.2,
  2012,33.4,
  2011,32.8,
  2010,32.8,
  2009,38.5,
  2008,37.2,
  2007,35.8,
  2006,37.5,
  2005,40.3,
  2004,35.2,
)

ggplot(three, aes(x = Season, y = pct, label = pct)) +
  geom_line(color = "#e6cab1") +
  geom_point() +
  geom_text(aes(label = sprintf("%0.1f", round(pct, digits = 1))), 
            color = "#13294B",
            size = 4, fontface = "bold", vjust = -2.5) +
  geom_vline(xintercept = 2008.5, lty = 2) +
  geom_vline(xintercept = 2019.5, lty = 2) +
  scale_x_continuous(breaks = seq(2004, 2021, 1)) +
  ylim(25, 45) +
  theme_me() +
  theme(legend.position = "none") +
  annotate(
    "text",
    x = 2015,
    y = 40,
    label = "Three-point was \n moved back prior to \n 2008-09 and \n 2019-20 seasons",
    family = "Chalkboard Bold",
    size = 4,
    color = "#EF426F"
  ) +
   annotate(
    geom = "curve", color = "#EF426F", x = 2019, y = 27, xend = 2020.8, yend = 26.5, 
    curvature = .3, arrow = arrow(length = unit(2, "mm"))
  ) +
  annotate(geom = "text", x = 2018.8, y = 28, label = "24-89 through \n six games", family = "Chalkboard Bold", size = 4, color = "#EF426F") +
  labs(
    x = "Season",
    y = "Three-point percentage",
    title = "Carolina Offense: Three-Point Percentage Since 2004",
    subtitle = "Season-by-season during the Roy Williams Era (since 2004). 2020-21 season is only six games old.",
    caption = "@dadgumboxscores"
  )
```

Carolina has made 24 of 89 three-point shots through six games. 

That is a putrid ~27 percent. 

This annotated line chart shows how that incomplete sample size compares to past season three-point percentages in the Roy Williams Era, including when the line was moved back. 

Code is below . . .

```
library(ggplot2)

theme_me <- function () {
  theme_minimal(base_size = 15, base_family = "RobotoCondensed-Regular") %+replace%
    theme (
      plot.title = element_text(hjust = 0.5),
      plot.subtitle = element_text(
        hjust = 0.5,
        vjust = -2,
        lineheight = 0.9,
        size = 10
      ),
      plot.caption = element_text(size = 8, hjust = 1),
      panel.grid.minor = element_blank(),
      plot.background = element_rect(fill = "#c9e1f1", color = "#c9e1f1")
    )
}

three <- tibble::tribble(
  ~Season,~pct,
  2021,27.0,
  2020,30.4,
  2019,36.2,
  2018,35.9,
  2017,35.5,
  2016,32.7,
  2015,35.8,
  2014,33.6,
  2013,37.2,
  2012,33.4,
  2011,32.8,
  2010,32.8,
  2009,38.5,
  2008,37.2,
  2007,35.8,
  2006,37.5,
  2005,40.3,
  2004,35.2,
)

ggplot(three, aes(x = Season, y = pct, label = pct)) +
  geom_line(color = "#e6cab1") +
  geom_point() +
  geom_text(aes(label = sprintf("%0.1f", round(pct, digits = 1))), 
            color = "#13294B",
            size = 4, fontface = "bold", vjust = -2.5) +
  geom_vline(xintercept = 2008.5, lty = 2) +
  geom_vline(xintercept = 2019.5, lty = 2) +
  scale_x_continuous(breaks = seq(2004, 2021, 1)) +
  ylim(25, 45) +
  theme_me() +
  theme(legend.position = "none") +
  annotate(
    "text",
    x = 2015,
    y = 40,
    label = "Three-point was \n moved back prior to \n 2008-09 and \n 2019-20 seasons",
    family = "Chalkboard Bold",
    size = 4,
    color = "#EF426F"
  ) +
   annotate(
    geom = "curve", color = "#EF426F", x = 2019, y = 27, xend = 2020.8, yend = 26.5, 
    curvature = .3, arrow = arrow(length = unit(2, "mm"))
  ) +
  annotate(geom = "text", x = 2018.8, y = 28, label = "24-89 through \n six games", family = "Chalkboard Bold", size = 4, color = "#EF426F") +
  labs(
    x = "Season",
    y = "Three-point percentage",
    title = "Carolina Offense: Three-Point Percentage Since 2004",
    subtitle = "Season-by-season during the Roy Williams Era (since 2004). 2020-21 season is only six games old.",
    caption = "@dadgumboxscores"
  )
```
